Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.68.68"

  config.vm.synced_folder "./docker", "/docker", type: "smb", owner: "root", group: "root"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "3072"
  end
  
  config.vm.provision "shell", path: "bootstrap.sh"
end
